version: '2'
services:
  dwh:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRESQL_PASSWORD: postgres_password
      POSTGRESQL_USER: review
      POSTGRESQL_DB: postgres_db
    ports:
      - 5432:5432
  db:
    image: mysql
    ports:
      - "3306:3306"
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/review
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: review_development
      MYSQL_USER: review
      MYSQL_PASSWORD: mysql_password

volumes:
  db_data: