version: '3'
services:
  dwh:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRESQL_PASSWORD: postgres_password
      POSTGRESQL_USER: review
      POSTGRESQL_DB: postgres_db
    ports:
      - 5432:5432
  db:
    image: mysql
    ports:
      - "3306:3306"
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/review
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: review_production
      MYSQL_USER: review
      MYSQL_PASSWORD: mysql_password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .: /review
    ports:
      - "3000:3000"
    depends_on:
      - db
      - dwh

volumes:
  db_data: